package Object

import androidx.compose.runtime.Composable

var sizehd: Int = 0
var sizedg: Int = 0

var Dongeng: List<HalamanBelajar> = listOf()
var Hadist: List<HalamanBelajar> = listOf()



@Composable
fun Data(){
    //    Untuk penempatan kata pada data :
    //    text arab di simpan dalam bentuk String of array seperti contoh dibawah
    //    text indonesia juga sama di simpan dalam bentuk String of array seperti contoh dibawah
    //    untuk lokasi logat dapat di simpan dalam bentuk array of tripple
    //    Keterangan warna:
    //          1 = red
    //          2 = blue
    //          3 = brown
    //          4 = purple

    var Array_arab = arrayOf<String>()
    var Array_indo = arrayOf<String>()
    var Array_logat = arrayOf<Quadruple<Int, Int, Int, String>>()
    var ArtiFull: String = ""
    var Penjelasan: String = ""
    var Array_logat_B = arrayOf<Pair<Int, String>>()
    var Array_Duplicate = arrayOf<Pair<Int, Int>>()
    var iterasi: Int = 0

    fun clearArrays() {
        Array_arab = arrayOf<String>()
        Array_indo = arrayOf<String>()
        Array_logat = arrayOf<Quadruple<Int, Int, Int, String>>()
        ArtiFull = ""
        Penjelasan = ""
        Array_logat_B = arrayOf<Pair<Int, String>>()
        Array_Duplicate = arrayOf<Pair<Int, Int>>()
        iterasi = 0
    }


    fun init_arabic(){
        for (i in Array_arab.indices) {
            Array_arab[i] = Array_arab[i] + " "
        }
    }

//    untuk penggunaan array pakai saja yang diatas supaya tidak perlu menulis ulang (nambah memori)

//    hadits
//    hadist 1
    Array_arab += "إليْه"
    Array_arab += "هَاجَرَ"
    Array_arab += "ما"
    Array_arab += "إلى"
    Array_arab += "فهِجْرَ تُهُ"
    Array_arab += "يَنْكِحُهَا"
    Array_arab += "امرأةٍ"
    Array_arab += "أو"
    Array_arab += "يُصِيْبُهَا" //40
    Array_arab += "لِدُنْيَا"
    Array_arab += "هِجْرَتُهُ"
    Array_arab += "كَانَتْ"
    Array_arab += "مَنْ"// 36
    Array_arab += "و"
    Array_arab += "رَسُوْلِهِ"
    Array_arab += "و"
    Array_arab += "اللهِ"
    Array_arab += "إلى"
    Array_arab += "فَهِجْرَتُهُ"
    Array_arab += "رَسُولِهِ"
    Array_arab += "و"
    Array_arab += "اللهِ"
    Array_arab += "إلى"
    Array_arab += "هِجْرَ تُهُ"
    Array_arab += "كَانَتْ"
    Array_arab += "فَمَنْ"
    Array_arab += "نَوَى"
    Array_arab += "ما"
    Array_arab += "امريءٍ"
    Array_arab += "لِكُلِّ"
    Array_arab += "إِنَّما"
    Array_arab += "و"
    Array_arab += "بِالنِّيَّاتِ"
    Array_arab += "الأعمَالُ"
    Array_arab += "إنَّمَا"
    Array_arab += "سَلَّمَ"
    Array_arab += "و" //12
    Array_arab += "عليه"
    Array_arab += "الله"
    Array_arab += "صلّى"
    Array_arab += "رَسُوْلَ اللهِ"
    Array_arab += "سَمِعْتُ"
    Array_arab += "قَالَ"
    Array_arab += "عَنْهُ"
    Array_arab += "اللهُ"
    Array_arab += "رَضِيَ"
    Array_arab += "أَبِيْ حَفْصٍ عُمَرَ بْنِ الْخَطَّابِ"
    Array_arab += "أَمِيْرِالْمُؤْمِنِيْنَ"
    Array_arab += "عن"
    init_arabic()

    Array_indo += "Kepadanya"
    Array_indo += "Ia hijrah"

    Array_indo += "Apa"
    Array_indo += "Kepada"
    Array_indo += "Maka hijrahnya"
    Array_indo += "Yang dinikahinya"
    Array_indo += "Perempuam"
    Array_indo += "Atau"
    Array_indo += "Mencarinya"

    Array_indo += "Bagi dunia"
    Array_indo += "Hijrahnya"
    Array_indo += "Keadaan"
    Array_indo += "Barang siapa"
    Array_indo += "Dan"
    Array_indo += "Rasulnya"
    Array_indo += "Dan"

    Array_indo += "Allah"
    Array_indo += "Kepada"
    Array_indo += "Maka hijrahnya"
    Array_indo += "Rasul-Nya"
    Array_indo += "Dan"
    Array_indo += "Allah"
    Array_indo += "Kepada"

    Array_indo += "Hijrahnya"
    Array_indo += "Keadaan"
    Array_indo += "Maka barang siapa"
    Array_indo += "Ia niatkan"
    Array_indo += "Apa-apa"
    Array_indo += "Orang"
    Array_indo += "Bagi setiap"

    Array_indo += "Hanya saja"
    Array_indo += "Dan"
    Array_indo += "(Tergantung)dengan niat"
    Array_indo += "Amal-amal itu"
    Array_indo += "Hanya saja"
    Array_indo += "Salam"
    Array_indo += "Dan"
    Array_indo += "Pada nabi muhammad"
    Array_indo += "Allah (limpahkan)"

    Array_indo += "Semoga shalawat"
    Array_indo += "Rasulullah"
    Array_indo += "Aku mendengar"
    Array_indo += "Ia berkata"
    Array_indo += "Padanya"
    Array_indo += "Allah"
    Array_indo += "Semoga meridhoi"
    Array_indo += "Abi Hafs Umar bin Khatthab"
    Array_indo += "Pemimpin bagi orang-orang beriman"
    Array_indo += "Dari"

//    Array_logat += Triple(3,1,1)
    for (i in 0..5){
        Array_logat += Quadruple(3,i,2,"P2")
        iterasi++
    }

    for (i in 0..4){
        Array_logat += Quadruple(4,i,1, "S2")
        iterasi++
    }

    for (i in 0..4){
        Array_logat += Quadruple(6,i,2, "P2")
        iterasi++
    }

    for (i in 0..13){
        Array_logat += Quadruple(8,i,3, "O")
        iterasi++
    }

    for (i in 0..4){
        Array_logat += Quadruple(9,i,3, "O")
        iterasi++
    }

    for (i in 0..4){
        Array_logat += Quadruple(10,i,3, "O")
        iterasi++
    }

    for (i in 0..4){
        Array_logat += Quadruple(11,i,3, "O")
        iterasi++
    }

    for (i in 0..1){
        Array_logat += Quadruple(12,i,3, "O")
        iterasi++
    }

    for (i in 0..6){
        Array_logat += Quadruple(13,i,3, "O")
        iterasi++
    }

    for (i in 0..8){
        Array_logat += Quadruple(15,i,1, "S1")
        iterasi++
    }

    for (i in 0..12){
        Array_logat += Quadruple(16,i,2, "P1")
        iterasi++
    }

    //contoh doang duplikat ada di arr 11
//    for (i in 7..12){
//        Array_logat += Quadruple(16,i,1, "S2")
//        iterasi++
//    }
//    Array_Duplicate += Pair(16,iterasi - 1)

    for (i in 2..5){
        Array_logat += Quadruple(23,i,1, "S1")
    }

    for (i in 0..3){
        Array_logat += Quadruple(36,i,1, "S1")
    }

    for (i in 0..11){
        Array_logat += Quadruple(40,i,2, "P2")
    }

    for (i in 0..11){
        Array_logat += Quadruple(43,i,2, "P2")
    }

    for (i in 0..6){
        Array_logat += Quadruple(47,i,2, "P2")
    }

    val uniqueFirstElements = Array_logat.map { it.first }.toSet()
    val resultArray = uniqueFirstElements.map { uniqueElement ->
        val index = Array_logat.indexOfFirst { it.first == uniqueElement }
        Pair(uniqueElement, index)
    }.toTypedArray()

    Array_logat_B += Pair(0,"Pp")
    Array_logat_B += Pair(1,"N1")
    Array_logat_B += Pair(2,"N1")
    Array_logat_B += Pair(3,"Vl")
    Array_logat_B += Pair(4,"Pp")
    Array_logat_B += Pair(6,"Vl")
    Array_logat_B += Pair(8,"N1")
    Array_logat_B += Pair(15,"N")
    Array_logat_B += Pair(16,"Pp")
    Array_logat_B += Pair(17,"Ko")
    Array_logat_B += Pair(26,"Pp")
    Array_logat_B += Pair(28,"Ko")
    Array_logat_B += Pair(30,"Ko")
    Array_logat_B += Pair(33,"Pp")
    Array_logat_B += Pair(35,"Ko")
    Array_logat_B += Pair(39,"Pp")
    Array_logat_B += Pair(40,"Vnl")
    Array_logat_B += Pair(41,"Ko")
    Array_logat_B += Pair(42,"N1")
    Array_logat_B += Pair(43,"Vnl")
    Array_logat_B += Pair(45,"Pp")
    Array_logat_B += Pair(47,"Vl")
    Array_logat_B += Pair(48,"Pp")

    ArtiFull = "Dari Amirul Mukminin, Abu Hafsh ‘Umar bin Al-Khattab radhiyallahu ‘anhu, ia berkata bahwa ia mendengar Rasulullah shallallahu ‘alaihi wa sallam bersabda: “Sesungguhnya setiap amalan tergantung pada niatnya. Setiap orang akan mendapatkan apa yang ia niatkan. Siapa yang hijrahnya karena Allah dan Rasul-Nya, maka hijrahnya untuk Allah dan Rasul-Nya. Siapa yang hijrahnya karena mencari dunia atau karena wanita yang dinikahinya, maka hijrahnya kepada yang ia tuju.”"
    Penjelasan = "\nPenjelasan hadist\n" +
            "\n" + "Niat artinya bermaksud atau berkehendak. Sebagian ulama bersepakat bahwa niat itu letaknya di hati. Jika seseorang berniat dalam hatinya tanpa dilafazhkan, maka niatnya dianggap sah. \n" +
            "Suatu amalan ada dikarenakan ada niatnya. Jika seseorang melakukan pekerjaan tanpa niat, maka seperti orang yang tertidur atau gila. \n" +
            "Setiap orang memperoleh pahala sesuai dengan apa yang ia niatkan. \n" +
            "Hijrah itu artinya berpindah atau meninggalkan tempat, dapat diartikan pula berpindah dari maksiat menuju ketaatan. \n" +
            "Dalam beramal perlu niat yang ikhlas.\n"

    val hadist1: HalamanBelajar = HalamanBelajar("Hadist Arbain No. 1", "Setiap Amalan Tergantung Pada Niat", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

    // hadist 2





    Hadist += listOf(hadist1)

//    Dongeng
//    Contoh buat dongeng:


//    Dongeng 1
    Array_arab += "فِيهِ"
    Array_arab += "دَفْنُهَا"
    Array_arab += "تَمَّ"
    Array_arab += "وَ"
    Array_arab += "تَالَاجَا"
    Array_arab += "فِي"
    Array_arab += "الْمُتَوَفَّى"
    Array_arab += "بَالُونَا"
    Array_arab += "الْأَمِيرَةَ"
    Array_arab += "سَمَّيَاهَا"
    Array_arab += "طِفْلَةً"
    Array_arab += "وَهَبَا"
    Array_arab += "وَ"
    Array_arab += "فَتَزَوَّجَا"
    Array_arab += "مَرَضِهَا"
    Array_arab += "إِزَالَةِ"
    Array_arab += "وَ"
    Array_arab += "الْأَمِيرَةِ"
    Array_arab += "عِلَاجِ"
    Array_arab += "فِي"
    Array_arab += "يُقَدَّرُ"
    Array_arab += "عَالِمٍ"
    Array_arab += "رَجُلٍ"
    Array_arab += "بِحُضُورِ"
    Array_arab += "الْقَدْرُ"
    Array_arab += "تَمَّ"
    Array_arab += "لَهَا"
    Array_arab += "زَوْجًا"
    Array_arab += "تَتَّخِذُهَا"
    Array_arab += "فَسَوْفَ"
    Array_arab += "رَجُلًا"
    Array_arab += "الشَّخْصُ"
    Array_arab += "كَانَ"
    Array_arab += "إِذَا"
    Array_arab += "أَمَّا"
    Array_arab += "أُمًّا"
    Array_arab += "فَسَتَتَّخِذُهَا"
    Array_arab += "الْعُمْرِ"
    Array_arab += "مِنْ"
    Array_arab += "تَبْلُغُ"
    Array_arab += "سَيِّدَةٌ"
    Array_arab += "كَانَ"
    Array_arab += "فَإِذَا"
    Array_arab += "مَرَضَهَا"
    Array_arab += "أَنْ يُزِيلَ"
    Array_arab += "عَلَى"
    Array_arab += "قَادِرٍ"
    Array_arab += "شَخْصٍ"
    Array_arab += "أَيَّ"
    Array_arab += "وَجَدْتَ"
    Array_arab += "إِذَا"
    Array_arab += "أَنَّهُ"
    Array_arab += "سِيمْبِرْكَنِتْشَانَا"
    Array_arab += "فَاقْسَمْتْ"
    Array_arab += "مُزْمِنًا"
    Array_arab += "مَرَضًا"
    Array_arab += "عَانَى"
    Array_arab += "حَتَّى"
    Array_arab += "بِالِانْقَامِ"
    Array_arab += "الْغَضَبُ"
    Array_arab += "لَمْ يَذْهَبْ"
    Array_arab += "وَ"
    Array_arab += "الشَّدِيدِ"
    Array_arab += "بِالْغَضَبِ"
    Array_arab += "تَشْعُرُ"
    Array_arab += "سِيمِيرْ كِنْتْشَانَا"
    Array_arab += "كَانَتْ"
    Array_arab += "ذَلِكَ"
    Array_arab += "وَبِجَانِبِ"
    Array_arab += "دَبُّوسٍ"
    Array_arab += "بِاسْتِخْدَامِ"
    Array_arab += "رَقَبَتِهِ"
    Array_arab += "فِي"
    Array_arab += "طَعَنَتْهُ"
    Array_arab += "حَيْثُ"
    Array_arab += "يَنَامُ"
    Array_arab += "حِينَ"
    Array_arab += "سِيمِيرْكَنْتْشَانَا"
    Array_arab += "فَقَتَلَتْهُ"
    Array_arab += "الزَّوْجِ"
    Array_arab += "مِنْ"
    Array_arab += "بِالِانْتِقَامِ"
    Array_arab += "الْأَمِيرَةُ"
    Array_arab += "تَشْعُرَ"
    Array_arab += "حَتَّى"
    Array_arab += "زَوْجِهَا"
    Array_arab += "خُدْعَةَ"
    Array_arab += "أَدْرَكَتْ"
    Array_arab += "قَدْ"
    Array_arab += "سِيمِيرْكَنْتِشَانَا"
    Array_arab += "الْأَمِيرَةُ"
    Array_arab += "كَانَتْ"
    Array_arab += "أَيْضًا"
    Array_arab += "بِسَبَبِهَا"
    Array_arab += "مَاتَ"
    Array_arab += "حَتَّى"
    Array_arab += "الشَّدِيدَةَ"
    Array_arab += "الصَّدْمَةَ"
    Array_arab += "تِشَانْتَانْجْ بَارَانْج"
    Array_arab += "أَصَابَتْ"
    Array_arab += "الْمَلِكِ"
    Array_arab += "قَتْلِ"
    Array_arab += "بَعْدَ"
    Array_arab += "أَنَّهُ"
    Array_arab += "إِلَّا"
    Array_arab += "تِشَانْتَانْجْ بَارَانْج"
    Array_arab += "يَدِ"
    Array_arab += "عَلَى"
    Array_arab += "الْمَلِكِ"
    Array_arab += "قَتْلُ"
    Array_arab += "تَمَّ"
    Array_arab += "وَأَخِيرًا"
    Array_arab += "الْمَلِكِ"
    Array_arab += "لِقَتْلِ"
    Array_arab += "تِشَانْتَائِجْ بَارَاتْج"
    Array_arab += "مِنْ"
    Array_arab += "النَّائِبُ"
    Array_arab += "فَطَلَبَ"
    Array_arab += "لِزَوْجَتِهِ"
    Array_arab += "أَبٌ"
    Array_arab += "هُوَ"
    Array_arab += "الَّذِى"
    Array_arab += "الْمَلْكِ"
    Array_arab += "قَتْلُ"
    Array_arab += "إِلَّا"
    Array_arab += "لَيْسَ"
    Array_arab += "الْغَرَضِ"
    Array_arab += "هَذَا"
    Array_arab += "إِلَى"
    Array_arab += "الْوَحِيدُ"
    Array_arab += "وَ الطَّرِيقُ"
    Array_arab += "شَرْعِيٍّ"
    Array_arab += "غَيْرِ"
    Array_arab += "بِطَرِيقٍ"
    Array_arab += "مَلْكًا"
    Array_arab += "أَنْ يَكُونَ"
    Array_arab += "يُرِيدُ"
    Array_arab += "حَيْثُ"
    Array_arab += "حَاسِدًا"
    Array_arab += "خَادِعًا"
    Array_arab += "قَلْبًا"
    Array_arab += "لِلنَّائِبِ"
    Array_arab += "أَنَّ"
    Array_arab += "وَرَوَى"
    Array_arab += "الْفُرْسَانِ"
    Array_arab += "وَ"
    Array_arab += "أَصْحَابِ الْقُوَّةِ"
    Array_arab += "مِنْ"
    Array_arab += "الضُّيُوفِ"
    Array_arab += "مِنْ"
    Array_arab += "كَبِيرٌ"
    Array_arab += "عَدَدٌ"
    Array_arab += "الْعُرُوشِ"
    Array_arab += "حَفْلَةِ"
    Array_arab += "فِي"
    Array_arab += "حَضَرَ"
    Array_arab += "حَيْثُ"
    Array_arab += "بَالِينْبَاتِجْ جُونُونْجْ"
    Array_arab += "الْمَلِكِ"
    Array_arab += "نَائِبِ"
    Array_arab += "مَعَ"
    Array_arab += "تَزْوِيجُهَا"
    Array_arab += "تَمَّ"
    Array_arab += "الَّتِي"
    Array_arab += "الْبِنْتُ الصُّغْرَى"
    Array_arab += "إِلَّا"
    Array_arab += "قَصْرِ الْمَمْلَكَةِ"
    Array_arab += "فِي"
    Array_arab += "لَيْسَ"
    Array_arab += "بِيتُونْجْ جَبْلِ"
    Array_arab += "فِي"
    Array_arab += "قِمَّةِ"
    Array_arab += "لِلتَّحَنُّثِ"
    Array_arab += "رَادْینْ بَانْجِلُورَاهْ"
    Array_arab += "ذَهَبَ"
    Array_arab += "بِاخْتِصَارِ شَدِیدٍ"
    Array_arab += "سِيمِيرْ كَنْتْشَانَا"
    Array_arab += "اسْمُهُ"
    Array_arab += " وَالِابْنُ الْأَصْغَرُ"
    Array_arab += "رَادِينْ بِالْمَخْلُورَاهِ"
    Array_arab += "اسْمُهُ"
    Array_arab += "الِابْنُ الْأَكْبَرُ"
    Array_arab += "ابْنَانِ"
    Array_arab += "لِلْمَلِكِ"
    Array_arab += "كَانَ"
    Array_arab += "تَالَانْجْ مَانْجُونْج"
    Array_arab += "اسْمُهَا"
    Array_arab += "مَمْلَكَةً"
    Array_arab += "مَايْ"
    Array_arab += "تُشِيرُ"
    Array_arab += "جَبَلِ"
    Array_arab += "فِي وَادِي"
    Array_arab += "مِنْ الْعُصُورِ الْقَدِيمَةِ"
    Array_arab += "فِي عَصْرٍ"
    init_arabic()

    Array_indo += "Padanya"
    Array_indo += "Makamnya"
    Array_indo += "Telah selesai"
    Array_indo += "dan"
    Array_indo += "Talaga"
    Array_indo += "di"
    Array_indo += "yang telah meninggal"
    Array_indo += "Baluna"
    Array_indo += "Putri"
    Array_indo += "Yang bernama"
    Array_indo += "Seorang anak"
    Array_indo += "(mereka berdua) dikaruniai"
    Array_indo += "dan"
    Array_indo += "Maka (mereka berdua) menikah"
    Array_indo += "Penyakitnya"
    Array_indo += "menyembuhkan"
    Array_indo += "dan"
    Array_indo += "Ratu (Simbarkancana)"
    Array_indo += "mengobati"
    Array_indo += "dalam"
    Array_indo += "(ia) mampu"
    Array_indo += "Yang mengetahui"
    Array_indo += "Seorang laki-laki"
    Array_indo += "Dengan kedatangan"
    Array_indo += "Mampu"
    Array_indo += "Selesai (singkat cerita)"
    Array_indo += "Baginya"
    Array_indo += "Suami"
    Array_indo += "Dijadikannya"
    Array_indo += "Maka akan"
    Array_indo += "Laki-laki"
    Array_indo += "Seorang"
    Array_indo += "Adalah"
    Array_indo += "Jika"
    Array_indo += "Adapun"
    Array_indo += "Ibu"
    Array_indo += "Ia akan dijadikannya"
    Array_indo += "Umur"
    Array_indo += "Dari"
    Array_indo += "(ia) sampai"
    Array_indo += "Wanita"
    Array_indo += "Adalah"
    Array_indo += "Jika"
    Array_indo += "Penyakitnya"
    Array_indo += "Menyembuhkan"
    Array_indo += "Atas"
    Array_indo += "Yang mampu"
    Array_indo += "Seseorang"
    Array_indo += "yaitu"
    Array_indo += "(kau) dapat"
    Array_indo += "Barangsiapa"
    Array_indo += "Bahwasanya"
    Array_indo += "Simbarkancana"
    Array_indo += "Maka bersumpah"
    Array_indo += "Yang kronis"
    Array_indo += "Penyakit"
    Array_indo += "(ia) menderita"
    Array_indo += "Sehingga"
    Array_indo += "Dengan balas dendam"
    Array_indo += "Sakit hati"
    Array_indo += "tidak berlalu"
    Array_indo += "dan"
    Array_indo += "sangat"
    Array_indo += "sakit hati"
    Array_indo += "(ia) merasa"
    Array_indo += "Simbarkancana"
    Array_indo += "Adalah"
    Array_indo += "itu"
    Array_indo += "Di samping"
    Array_indo += "Konde"
    Array_indo += "Dengan menggunakan"
    Array_indo += "Lehernya"
    Array_indo += "pada"
    Array_indo += "(ia) menusukkannya"
    Array_indo += "dimana"
    Array_indo += "(ia) tidur"
    Array_indo += "Ketika"
    Array_indo += "Simbarkencana"
    Array_indo += "Maka (ia) membunuh (nya)"
    Array_indo += "Suaminya"
    Array_indo += "Kepada"
    Array_indo += "Dendam"
    Array_indo += "Ratu (istrinya)"
    Array_indo += "Merasa"
    Array_indo += "Sehingga"
    Array_indo += "Suaminya"
    Array_indo += "Keculasan"
    Array_indo += "(ia) mengetahui"
    Array_indo += "Sungguh"
    Array_indo += "Simbarkencana"
    Array_indo += "Ratu (istrinya)"
    Array_indo += "Adalah"
    Array_indo += "Juga"
    Array_indo += "Penyebabnya"
    Array_indo += "(ia) mati"
    Array_indo += "Sehingga"
    Array_indo += "Keras"
    Array_indo += "Pukulan"
    Array_indo += "Centangbarang"
    Array_indo += "(ia) terkena"
    Array_indo += "Raja"
    Array_indo += "Membunug"
    Array_indo += "setelah"
    Array_indo += "Bahwasannya (ia)"
    Array_indo += "tetapi"
    Array_indo += "Centangbarang"
    Array_indo += "tangan"
    Array_indo += "atas"
    Array_indo += "raja"
    Array_indo += "membunuh"
    Array_indo += "selesai"
    Array_indo += "Akhirnya"
    Array_indo += "Raja"
    Array_indo += "Untuk membunuh"
    Array_indo += "Centangbarang"
    Array_indo += "Kepada"
    Array_indo += "Pengganti itu (Patih Palembanggunung)"
    Array_indo += "Maka (ia) menyuruh"
    Array_indo += "Isterinya"
    Array_indo += "Ayah"
    Array_indo += "Dia itu"
    Array_indo += "yang"
    Array_indo += "raja"
    Array_indo += "membunuh"
    Array_indo += "kecuali"
    Array_indo += "tidaklah"
    Array_indo += "tercapai"
    Array_indo += "ini"
    Array_indo += "agar"
    Array_indo += "Salah satu"
    Array_indo += "cara"
    Array_indo += "Sesuai hukum"
    Array_indo += "tidak"
    Array_indo += "Dengan cara"
    Array_indo += "Seorang raja"
    Array_indo += "menjadi"
    Array_indo += "(dia) ingin"
    Array_indo += "dimana"
    Array_indo += "Dengki"
    Array_indo += "Culas"
    Array_indo += "berhati"
    Array_indo += "Pengganti itu (Patih Palembanggunung)"
    Array_indo += "bahwasannya"
    Array_indo += "Diceritakan"
    Array_indo += "Para ksatria"
    Array_indo += "dan"
    Array_indo += "Tamu agung"
    Array_indo += "dari"
    Array_indo += "Para tamu"
    Array_indo += "dari"
    Array_indo += "(yang) besar (banyak)"
    Array_indo += "jumlah"
    Array_indo += "Perkawinan"
    Array_indo += "Upacara"
    Array_indo += "pada"
    Array_indo += "Telah datang"
    Array_indo += " "
    Array_indo += "Palembanggunung."
    Array_indo += "Raja"
    Array_indo += "Pengganti"
    Array_indo += "bersama"
    Array_indo += "Menikah (dengannya)"
    Array_indo += "Sudah"
    Array_indo += "Yang"
    Array_indo += "Putri bungsu"
    Array_indo += "Kecuali"
    Array_indo += "Keraton"
    Array_indo += "Di"
    Array_indo += "Tidaklah"
    Array_indo += "Bitung"
    Array_indo += "Gunung"
    Array_indo += "Di puncak"
    Array_indo += "Untuk bertapa"
    Array_indo += "Raden Panglurah"
    Array_indo += "Telah pergi"
    Array_indo += "Singkat cerita"
    Array_indo += "Simbarkancana"
    Array_indo += "Namanya"
    Array_indo += "Dan putra bungsu"
    Array_indo += "Raden Panglurah"
    Array_indo += "Namanya"
    Array_indo += "Putra sulung"
    Array_indo += "Dua orang putra"
    Array_indo += "Raja itu (Memiliki)"
    Array_indo += "Adalah"
    Array_indo += "Talagamanggung"
    Array_indo += "Namanya"
    Array_indo += "Kerajaan"
    Array_indo += "Ciremai"
    Array_indo += "Ada (memberi isyarat)"
    Array_indo += "Gunung"
    Array_indo += "Di lembah"
    Array_indo += "Zaman dahulu"
    Array_indo += "Pada zaman"

    ArtiFull = "Pada zaman dahulu di lembah Gunung Ciremai ada sebuah negara bernama Kerajaan Talagamanggung. Rajanya mempunyai dua orang putra. Yang sulung bernama Raden Panglurah dan yang bungsu bernama Simbarkancana.\n" +
            "\n" +
            "Singkat cerita Raden Panglurah pergi bertapa di Gunung Bitung (lima km dari Cikijing sebelah selatan). Yang ada di Keraton hanya Putri bungsu yang sudah menikah dengan Patih Palembanggunung. Upacara perkawinannya sangat meriah. Banyak tamu agung dan para ksatria yang datang.\n" +
            "\n" +
            "Diceritakan Patih Palembanggunung berhati culas. Dia ingin menjadi raja. Salah satu jalan supaya dia bisa jadi raja, yaitu dia harus bisa membunuh mertuanya (raja). Singkat cerita Patih Palembanggunung menyuruh Centangbarang untuk membunuh raja. Akhirnya, sang raja meninggal dibunuh oleh Centangbarang, tetapi akibatnya setelah raja meninggal Centangbarang kaget, yang pada akhirnya Centangbarang pun mati juga.\n" +
            "\n" +
            "Keculasan Patih Palembanggunung diketahui oleh istrinya, Putri Simbarkencana. Simbarkencana merasa dendam. Dan Patih Palembanggung dibunuh oleh Simbarkencana pada saat tidur dengan menggunakan konde yang ditusukkan ke leher Patih Palembanggunung.\n" +
            "\n" +
            "Simbarkancana sangat sakit hati, sampai akhirnya dia jatuh sakit. Saat itulah Simbarkancana bersumpah; barang siapa yang bisa menyembuhkannya dari penyakit, jika wanita tua akan dijadikan ibu, jika laki-laki akan dijadikan suami. Singkat cerita, Simbarkancana diobati oleh seorang Pandita dan sembuh. Mereka pun menikah dan dikaruniai seorang anak yang Bernama Putri Paluna, yang makamnya di Talaga.\n" +
            "\n"

    val dongeng1: HalamanBelajar = HalamanBelajar("تالاجا مانجونج", "1. Talagamanggung", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

//    Dongeng 2
    Array_arab += "أَنْدَارْ ، أَنْدَارْ"
    Array_arab += "عَنْ الطَّعَامِ"
    Array_arab += "لِلْبَحْثِ"
    Array_arab += "لِلْمُهَاجِرِينَ"
    Array_arab += "مَقْصِدًا"
    Array_arab += "صَارَ"
    Array_arab += "الْمَكَانَ"
    Array_arab += "هَذَا"
    Array_arab += "أَنَّ"
    Array_arab += "الِاسْمَ"
    Array_arab += "هَذَا"
    Array_arab += "يَعْنِي"
    Array_arab += "وَ"
    Array_arab += "بَاتْجَانْدَارَانْ"
    Array_arab += "إلَى"
    Array_arab += "الْمَكَانِ"
    Array_arab += "هَذَا"
    Array_arab += "اسْمُ"
    Array_arab += "تَحَوَّلَ"
    Array_arab += "عَلَى مَرِّ الزَّمَانِ"
    Array_arab += "وَأَخِيرًا"
    Array_arab += "الْعَيْشِ"
    Array_arab += "لُقْمَةِ"
    Array_arab += "أَجْلِ"
    Array_arab += "مِنْ"
    Array_arab += "مِنْطَقَةٍ"
    Array_arab += "خَارِجِ"
    Array_arab += "مِنْ"
    Array_arab += "يَأْتُونَ"
    Array_arab += "الَّذِينَ"
    Array_arab += "لِلنَّاسِ"
    Array_arab += "مَقْصِدًا"
    Array_arab += "الْمَكَانُ"
    Array_arab += "هَذَا"
    Array_arab += "أَصْبَحَ"
    Array_arab += "خِصْبٍ"
    Array_arab += "وَ"
    Array_arab += "آمْنٍ"
    Array_arab += "إِلَى وَضْعِ"
    Array_arab += "بُوجُونْجْ كَالَالَارْ"
    Array_arab += "بَحْرِ"
    Array_arab += "تَحَوُّلِ"
    Array_arab += "بَعْدَ"
    Array_arab += "آمِنًا"
    Array_arab += "الْمَكَانُ"
    Array_arab += "هَذَا"
    Array_arab += "يُصْبِحَ"
    Array_arab += "حَتَّى"
    Array_arab += "الْيَابَانِيِّ"
    Array_arab += "وَ"
    Array_arab += "الْهُولَنْدِيِّ"
    Array_arab += "الِاحْتِلَالِ"
    Array_arab += "عَصْرُ"
    Array_arab += "هُوَ"
    Array_arab += "وَ"
    Array_arab += "الِاحْتِلَالِ"
    Array_arab += "فَتْرَةَ"
    Array_arab += "الِاسْتِعْمَارِيَّةُ"
    Array_arab += "الْقُوَّةُ"
    Array_arab += "اسْتَخْدَمَتْهُ"
    Array_arab += "الَّذِي"
    Array_arab += "الْمَكَانُ"
    Array_arab += "أَنَّهُ"
    Array_arab += "بِمَعْنَى"
    Array_arab += "بُوجُونْجْ کالَالَارْ"
    Array_arab += "بَانْجَانْدَارَانْ"
    Array_arab += "بَحْرِ"
    Array_arab += "اسْمُ"
    Array_arab += "كَانَ"
    Array_arab += "الِبِدَايَةِ"
    Array_arab += "فِي"
    init_arabic()

    Array_indo += "Andar-andar"
    Array_indo += "Makanan"
    Array_indo += "Untuk mencari"
    Array_indo += "Bagi para pendatang"
    Array_indo += "Maksudnya"
    Array_indo += "Jadi"
    Array_indo += "Tempat"
    Array_indo += "Ini"
    Array_indo += "Bahwasanya"
    Array_indo += "Nama"
    Array_indo += "Ini"
    Array_indo += "Mempunyai arti"
    Array_indo += "dan"
    Array_indo += "Pangandaran"
    Array_indo += "Ke"
    Array_indo += "Tempat"
    Array_indo += "Ini"
    Array_indo += "Nama"
    Array_indo += "Berubah"
    Array_indo += "Lama kelamaan"
    Array_indo += "Akhirnya"
    Array_indo += "Hidup"
    Array_indo += "Untuk"
    Array_indo += "Alasan"
    Array_indo += "Dari"
    Array_indo += "Daerah"
    Array_indo += "Luar"
    Array_indo += "Dari"
    Array_indo += "(mereka) datang"
    Array_indo += "Yang"
    Array_indo += "Bagi banyak orang"
    Array_indo += "Tujuan"
    Array_indo += "Tempat"
    Array_indo += "Ini"
    Array_indo += "Menjadi"
    Array_indo += "Subur"
    Array_indo += "dan"
    Array_indo += "Aman"
    Array_indo += "Tempat"
    Array_indo += "Bojong Kalalar"
    Array_indo += "Laut"
    Array_indo += "Berubah"
    Array_indo += "Setelah"
    Array_indo += "Aman"
    Array_indo += "Tempat"
    Array_indo += "Ini"
    Array_indo += "Menjadi"
    Array_indo += "Sampai"
    Array_indo += "Jepang"
    Array_indo += "Dan"
    Array_indo += "Belanda"
    Array_indo += "Penjajahan"
    Array_indo += "Zaman"
    Array_indo += "Dia itu"
    Array_indo += "Dan"
    Array_indo += "Penjajahan"
    Array_indo += "Zaman"
    Array_indo += "Yang bersifat kolonial"
    Array_indo += "Kekuatan"
    Array_indo += "Yang mempergunakannya"
    Array_indo += "yang"
    Array_indo += "Tempat"
    Array_indo += "Bahwasannya ia"
    Array_indo += "Yang artinya"
    Array_indo += "Bojong Kalalar"
    Array_indo += "Pangandaran"
    Array_indo += "Laut"
    Array_indo += "Nama"
    Array_indo += "Ada"
    Array_indo += "Mulanya"
    Array_indo += "Pada"

    ArtiFull = "Pada mulanya, Pangandaran bernama Bojong Kalalar, yang artinya tempat yang hanya untuk dilewati musuh- musuh ketika zaman penjajah, yaitu ketika zaman Belanda dan Jepang, sampai tempat tersebut menjadi aman.\n" +
            "\n" +
            "Setelah maju, aman, serta subur, Bojong Kalalar berubah menjadi tempat mencari makanan sehingga banyak orang datang dari luar daerah. Akhirnya, lama kelamaan tempat itu berubah nama menjadi Pangan-daran, yang mempunyai arti tempat mencari makanan bagi para pendatang (andar-andar).\n" +
            "\n"

    val dongeng2: HalamanBelajar = HalamanBelajar("بانجانداران", "2. Pangandaran", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

//    Dongeng 3
    Array_arab += "إِلَى عَلَقَةٍ"
    Array_arab += "تَحَوَّلَتْ"
    Array_arab += "إِنَّهَا"
    Array_arab += "يَقُولُونَ"
    Array_arab += "أُنَاسٌ"
    Array_arab += "هُنَاكَ"
    Array_arab += "وَلَكِنْ"
    Array_arab += "نيني أَنْدِيتْ"
    Array_arab += "مَصِيرُ"
    Array_arab += "كَيْفَ"
    Array_arab += "يَعْرِفُ"
    Array_arab += "لَا أَحَدَ"
    Array_arab += "بُحَيْرَةً"
    Array_arab += "الْمَكَانُ"
    Array_arab += "هَذَا"
    Array_arab += "وَيُصْبِحُ"
    Array_arab += "ثَرْوَاتَهَا"
    Array_arab += "وَ"
    Array_arab += "نيني أَنْدِيتْ"
    Array_arab += "مَنْزِلَ"
    Array_arab += "الْمِيَاهُ"
    Array_arab += "أَغْرَقَتْ"
    Array_arab += "وَأَخِيرًا"
    Array_arab += "الْعَصَا"
    Array_arab += "هَذِهِ"
    Array_arab += "أَثَرَ"
    Array_arab += "الْأَرْضِ"
    Array_arab += "مِنْ"
    Array_arab += "الْغَزِيرُ"
    Array_arab += "الْمَاءُ"
    Array_arab += "تَبِعَ"
    Array_arab += "وَلَكِنْ"
    Array_arab += "مَرَّةً أُخْرَى"
    Array_arab += "سَحَبَهَا"
    Array_arab += "ثُمَّ"
    Array_arab += "نيني إِنْدِيتْ"
    Array_arab += "مَنْزِلِ"
    Array_arab += "سَاحَةِ"
    Array_arab += "فِي"
    Array_arab += "عَصَاهُ"
    Array_arab += "بِتَثْبِيتِ"
    Array_arab += "الْعَجُوزُ"
    Array_arab += "قَامَ"
    Array_arab += "مُغَادَرَتِهِ"
    Array_arab += "قَبْلَ"
    Array_arab += "وَبِلَحْظَةٍ"
    Array_arab += "الْكَلِمَاتِ"
    Array_arab += "هَذِهِ"
    Array_arab += "هُنَاكَ"
    Array_arab += "كَانُوا"
    Array_arab += "الَّذِينَ"
    Array_arab += "النَّاسِ"
    Array_arab += "مِنْ"
    Array_arab += "جَمْعُ غَفِيرٍ"
    Array_arab += "سَمِعَ"
    Array_arab += "وَ"
    Array_arab += "جَزَاؤُهُ"
    Array_arab += "هُنَاكَ"
    Array_arab += "فَإِنَّ"
    Array_arab += "عَلَى حَدٍّ سَوَاءٍ"
    Array_arab += "شَرًّا"
    Array_arab += "أَوْ"
    Array_arab += "كَانَ"
    Array_arab += "خَيْرًا"
    Array_arab += "عَمَلٍ"
    Array_arab += "كُلُّ"
    Array_arab += "الْعَجُوزُ"
    Array_arab += "قَالَ"
    Array_arab += "الْأَرْمَلَةُ"
    Array_arab += "مُغَادَرَتِهِ"
    Array_arab += "وَقَبْلَ"
    Array_arab += "مُتْعِبًا"
    Array_arab += "حَزِينًا"
    Array_arab += "الْعَجُوزُ"
    Array_arab += "انصرفَ"
    Array_arab += "الْمُغَادَرَةَ"
    Array_arab += "مِنْهُ"
    Array_arab += "طَلَبَتْ"
    Array_arab += "وَ"
    Array_arab += "طَرَدَتْهُ"
    Array_arab += "وَأَخِيرًا"
    Array_arab += "بِكَلَامٍ وَاحِشٍ"
    Array_arab += "الْعَجُوزِ"
    Array_arab += "بِتَوْبِيخِ"
    Array_arab += "نِيْنِيِّ إِنْدِيتْ"
    Array_arab += "قَامَتْ"
    Array_arab += "الْمَاءِ"
    Array_arab += "هَذَا"
    Array_arab += "عَلَى"
    Array_arab += "بَدَلًا مِنْ الْحُصُولِ"
    Array_arab += "وَلَكِنْ"
    Array_arab += "الْعَطَشِ"
    Array_arab += "بِسَبَبِ"
    Array_arab += "لِلشُّرْبِ"
    Array_arab += "الْمَاءِ"
    Array_arab += "مِنْ"
    Array_arab += "كُوبًا"
    Array_arab += "مِنْهَا"
    Array_arab += "يَطْلُبُ"
    Array_arab += "نِيْنِيِّ إِنْدِيتْ"
    Array_arab += "بَيْتِ"
    Array_arab += "إِلَى"
    Array_arab += "عَجُوزٌ"
    Array_arab += "جَاءَ"
    Array_arab += "وَ فِي يَوْمٍ مِنَ الْأَيَّامِ"
    Array_arab += "مُمْتَلَكَاتِهَا"
    Array_arab += "الْآخَرُونَ"
    Array_arab += "مَنْ أَنْ يَأْكُلَ"
    Array_arab += "خَوْفًا"
    Array_arab += "حُقُولِ الْأُرْزِّ"
    Array_arab += "وَسَطِ"
    Array_arab += "فِي"
    Array_arab += "مَنْزِلًا"
    Array_arab += "بَنَتْ"
    Array_arab += "وَ"
    Array_arab += "الْآخَرِينَ"
    Array_arab += "عَنْ"
    Array_arab += "نَفْسَهَا"
    Array_arab += "عَزَلَتْ"
    Array_arab += "الْعَمْدِيِّ"
    Array_arab += "الطَّرِيقِ"
    Array_arab += "عَلَى"
    Array_arab += "وَ"
    Array_arab += "وَحْدَهَا"
    Array_arab += "تَعِيشُ"
    Array_arab += "هِيَ"
    Array_arab += "وَ"
    Array_arab += "جِدًّا"
    Array_arab += "بَخِيلَةً"
    Array_arab += "وَكَانَتْ"
    Array_arab += "نِني إِنْدِيتْ"
    Array_arab += "اسْمُهَا"
    Array_arab += "غَنِيَّةٌ"
    Array_arab += "أَرْمَلَةٌ"
    Array_arab += "هُنَاكَ"
    Array_arab += "كَانَ"
    Array_arab += "الزَّمَانِ"
    Array_arab += "مِنَ"
    Array_arab += "قَدِيمٍ"
    Array_arab += "فِي"
    init_arabic()

    Array_indo += "Menjadi lintah"
    Array_indo += "Telah berubah"
    Array_indo += "Bahwasannya (Nyi endit)"
    Array_indo += "Mereka merkata"
    Array_indo += "Orang-orang"
    Array_indo += "Di sana"
    Array_indo += "tetapi"
    Array_indo += "Nyi endit"
    Array_indo += "nasib"
    Array_indo += "bagaimana"
    Array_indo += "mengetahui"
    Array_indo += "Tidak seorang pun"
    Array_indo += "Danau"
    Array_indo += "tempat"
    Array_indo += "ini"
    Array_indo += "menjadi"
    Array_indo += "kekayaannya"
    Array_indo += "dan"
    Array_indo += "Nyi endit"
    Array_indo += "Rumah"
    Array_indo += "Air"
    Array_indo += "menenggelamkan"
    Array_indo += "Akhirnya"
    Array_indo += "tongkat"
    Array_indo += "ini"
    Array_indo += "jejak"
    Array_indo += "tanah"
    Array_indo += "dari"
    Array_indo += "yang deras menggelegak"
    Array_indo += "Air"
    Array_indo += "mengikuti"
    Array_indo += "tetapi"
    Array_indo += "Sekali lagi"
    Array_indo += "Mencabutnya"
    Array_indo += "Kemudian"
    Array_indo += "Nyi endit"
    Array_indo += "rumah"
    Array_indo += "pekarangan"
    Array_indo += "di"
    Array_indo += "tongkatnya"
    Array_indo += "Dengan menancapkan"
    Array_indo += "Kakek tua itu"
    Array_indo += "melakukan"
    Array_indo += "kepergiaannya"
    Array_indo += "sebelum"
    Array_indo += "sesaat"
    Array_indo += "Kata-kata"
    Array_indo += "ini"
    Array_indo += "Di sana"
    Array_indo += "Mereka itu ada"
    Array_indo += "yang"
    Array_indo += "Orang-orang"
    Array_indo += "dari"
    Array_indo += "semua"
    Array_indo += "mendengar"
    Array_indo += "dan"
    Array_indo += "balasannya"
    Array_indo += "Di sana"
    Array_indo += "bahwasannya"
    Array_indo += "keduanya"
    Array_indo += "jahat"
    Array_indo += "atau"
    Array_indo += ""
    Array_indo += "baik"
    Array_indo += "Perbuatan"
    Array_indo += "setiap"
    Array_indo += "Kakek tua itu"
    Array_indo += "Telah berkata"
    Array_indo += "Seorang janda"
    Array_indo += "kepergiannya"
    Array_indo += "sebelum"
    Array_indo += "Dan lelah"
    Array_indo += "Sambil tertatih-tatih (sedih)"
    Array_indo += "Kakek tua itu"
    Array_indo += "pergi"
    Array_indo += "pergi"
    Array_indo += "darinya"
    Array_indo += "Ia meminta"
    Array_indo += "dan"
    Array_indo += "(kakek) diusirnya"
    Array_indo += "Akhirnya"
    Array_indo += "Dengan habis-habisan"
    Array_indo += "Nenek tua"
    Array_indo += "memarahi"
    Array_indo += "Nyi Endit"
    Array_indo += "Melakukan"
    Array_indo += "Air"
    Array_indo += "ini"
    Array_indo += "atas"
    Array_indo += "Bukan mendapatkannya"
    Array_indo += "Akan tetapi"
    Array_indo += "haus"
    Array_indo += "karena"
    Array_indo += "untuk minum"
    Array_indo += "Air"
    Array_indo += "dari"
    Array_indo += "segelas"
    Array_indo += "darinya"
    Array_indo += "Ia meminta"
    Array_indo += "Nyi endit"
    Array_indo += "rumah"
    Array_indo += "ke"
    Array_indo += "Seorang kakek tua"
    Array_indo += "Datanglah"
    Array_indo += "Pada suatu hari"
    Array_indo += "hartanya"
    Array_indo += "Oleh (orang) lain"
    Array_indo += "dimakan"
    Array_indo += "Karena takut"
    Array_indo += "persawahan"
    Array_indo += "tengah"
    Array_indo += "di"
    Array_indo += "Sebuah rumah"
    Array_indo += "Ia membangun"
    Array_indo += "dan"
    Array_indo += "Orang lain"
    Array_indo += "dari"
    Array_indo += "Dirinya"
    Array_indo += "Ia mengasingkan"
    Array_indo += "sengaja"
    Array_indo += "cara"
    Array_indo += "dengan"
    Array_indo += "dan"
    Array_indo += "menyendiri"
    Array_indo += "hidup"
    Array_indo += "Dia"
    Array_indo += "dan"
    Array_indo += "sangat"
    Array_indo += "kikir"
    Array_indo += "Dan dia itu"
    Array_indo += "Nyi endit"
    Array_indo += "namanya"
    Array_indo += "Yang kaya"
    Array_indo += "Seorang janda"
    Array_indo += "Di sana"
    Array_indo += "ada"
    Array_indo += "zaman"
    Array_indo += "dari"
    Array_indo += "dahulu"
    Array_indo += "Pada"

    ArtiFull = "Zaman dahulu ada seorang janda kaya bernama Nyi Endit. la sangat kikir. Nyi Endit hidup menyendiri. Ia sengaja mengasingkan diri dengan membangun rumah di tengah persawahan yang luas. Maksudnya tiada lain agar ia tak mudah bergaul karena takut hartanya dimakan orang lain.\n" +
            "\n" +
            "Pada suatu hari datanglah seorang kakek tua ke rumah Nyi Endit. Kakek tua itu bermaksud meminta segelas air minum karena haus, tetapi Nyi Endit justru memarahinya habis- habisan. Akhirnya ia diusir, disuruh pergi. Kakek tua pun pergi sambil tertatih-tatih dan lunglai. Sebelum pergi ia berkata seperti ini. Apa pun, baik kepada orang yang baik maupun kepada orang yang jahat, akan selalu ada balasannya.\n" +
            "\n" +
            "Kata-kata kakek tua itu disaksikan oleh semua orang yang berada di situ. la berkata sambil menancapkan tongkatnya di pekarangan rumah Nyi Endit. Lalu tongkat itu dicabut kembali, tetapi dari dalam tanah keluar air yang deras menggelegak. Akhirnya, air itu menenggelamkan rumah Nyi Endit hingga menjadi danau. Menengggelamkan seluruh kekayaan Nyi Endit.\n" +
            "\n" +
            "Tidak ada yang tahu bagaimana nasib Nyi Endit, tetapi ada orang yang mengatakan bahwa Nyi Endit itu telah berubah menjadi lintah.\n" +
            "\n"

    val dongeng3: HalamanBelajar = HalamanBelajar("", "3. Situ Bagendit", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

//    Dongeng 4
    Array_arab += "يُرَافِقُهَا"
    Array_arab += "الْقَمَرِ"
    Array_arab += "إِلَى"
    Array_arab += "نِينِي أُنْتِيهْ"
    Array_arab += "ذَهَبَتْ"
    Array_arab += "وَأَخِيرَا"
    Array_arab += "رَغْبَتِهَا"
    Array_arab += "رَفْضِ"
    Array_arab += "عَلَى"
    Array_arab += "أَكِى بَالَانْجَانْتِرَانْجْ"
    Array_arab += "الزَّوْجُ"
    Array_arab += "لَنْ يُقَدِّرَ"
    Array_arab += "الْقَمَرِ"
    Array_arab += "فِي"
    Array_arab += "الْقُمَاشَ"
    Array_arab += "تَنْسِجُ"
    Array_arab += "سَوْفَ"
    Array_arab += "أَنَّهُ"
    Array_arab += "أَيْضًا"
    Array_arab += "وَقَالَتْ"
    Array_arab += "أَكِى بَالَانْجَانْتِرَانْجْ"
    Array_arab += "زَوْجِهَا"
    Array_arab += "إِلَى"
    Array_arab += "رَغْبَتَهَا"
    Array_arab += "نِينِي أُنْتِيه"
    Array_arab += "أَبْدَتْ"
    Array_arab += "يهِينُهُ"
    Array_arab += "مَنْ"
    Array_arab += "هُنَاكَ"
    Array_arab += "لَنْ يَكُونَ"
    Array_arab += "وَ"
    Array_arab += "سَاكِنٌ"
    Array_arab += "وَ"
    Array_arab += "مُطْمَئِنٌّ"
    Array_arab += "الْقَمَرِ"
    Array_arab += "فِي"
    Array_arab += "الْعَيْشَ"
    Array_arab += "أَنَّ"
    Array_arab += "تَتَخَيَّلُ"
    Array_arab += "وَكَانَتْ"
    Array_arab += "الْمُنِيرِ"
    Array_arab += "الْقَمَرِ"
    Array_arab += "إِلَى"
    Array_arab += "تَنْظُرُ"
    Array_arab += "نِينِي أَنْتِيهْ"
    Array_arab += "كَانَتْ"
    Array_arab += "الْبَدْرِ"
    Array_arab += "لَيْلَةِ"
    Array_arab += "فِي"
    Array_arab += "وَ"
    Array_arab += "بِوَضْعِهَا"
    Array_arab += "يَهْتَمُّ"
    Array_arab += "مَنْ"
    Array_arab += "هُنَاكَ"
    Array_arab += "لَمْ يَكُنْ"
    Array_arab += "الْجِيرَانُ"
    Array_arab += "مِنْهَا"
    Array_arab += "انْعَزَلَ"
    Array_arab += "حَتَّى"
    Array_arab += "الْبَأْسِ"
    Array_arab += "وَ"
    Array_arab += "فِي غَايَةِ الْفَقْرِ"
    Array_arab += "نِينِي أَنْتِيهْ"
    Array_arab += "حَيَاةُ"
    Array_arab += "كَانَتْ"
    Array_arab += "بِشَانْدِرَا مَاوَاتْ"
    Array_arab += "تَسْمِيَتُهَا"
    Array_arab += "تَمَّ"
    Array_arab += "وَاَلَّتِي"
    Array_arab += "الْمُلَوَّنَةِ"
    Array_arab += "قِطَطِ"
    Array_arab += "ثَلَاثَةَ"
    Array_arab += "يُرَاعَانِ"
    Array_arab += "الزَّوْجَانِ"
    Array_arab += "فَقَامَ"
    Array_arab += "طِفْلٌ"
    Array_arab += "لَدَيْهِمَا"
    Array_arab += "لَيْسَ"
    Array_arab += "أَيْضًا"
    Array_arab += "وَلَكِنْ"
    Array_arab += "أَكِي بَالَانْجَانْتِرَانْجْ"
    Array_arab += "مَعَ"
    Array_arab += "نِينِي"
    Array_arab += "تَزَوَّجَتْ"
    Array_arab += "طَوِيلٍ"
    Array_arab += "زَمَنٍ"
    Array_arab += "مُنْذُ"
    Array_arab += "نِينِي أَّنتيهْ"
    Array_arab += "بِاسْمِ"
    Array_arab += "تُعْرَفُ"
    Array_arab += "امْرَأَةٌ"
    Array_arab += "الْقَدِيمَةِ"
    Array_arab += "الْعُصُورِ"
    Array_arab += "فِي"
    Array_arab += "كَانَتْ"
    init_arabic()

    Array_indo += "Ditemaninya (oleh Candramawat)"
    Array_indo += "Bulan"
    Array_indo += "Ke"
    Array_indo += "Nini Anteh"
    Array_indo += "Telah pergi"
    Array_indo += "Akhirnya"
    Array_indo += "Keinginannya"
    Array_indo += "Penolakan"
    Array_indo += "Atas"
    Array_indo += "Aki Balangantrang"
    Array_indo += "Suami"
    Array_indo += "Tidak bisa"
    Array_indo += "Bulan"
    Array_indo += "Di"
    Array_indo += "Kain"
    Array_indo += "Menenun"
    Array_indo += "Akan"
    Array_indo += "Bahwasannya"
    Array_indo += "Juga"
    Array_indo += "Dan (ia) berkata"
    Array_indo += "Aki Balangantrang"
    Array_indo += "Suaminya"
    Array_indo += "Kepada"
    Array_indo += "Keinginannya"
    Array_indo += "Nini anteh"
    Array_indo += "Menyampaikan"
    Array_indo += "Menghinanya"
    Array_indo += "Seorang pun"
    Array_indo += "Di sana"
    Array_indo += "Tidaklah keadaan"
    Array_indo += "dan"
    Array_indo += "tentram"
    Array_indo += "dan"
    Array_indo += "tenang"
    Array_indo += "bulan"
    Array_indo += "di"
    Array_indo += "hidup"
    Array_indo += "bahwasannya"
    Array_indo += "(ia) membayangkan"
    Array_indo += "Dan adalah"
    Array_indo += "Yang terang"
    Array_indo += "bulan"
    Array_indo += "ke"
    Array_indo += "memandang"
    Array_indo += "Nini anteh"
    Array_indo += "adalah"
    Array_indo += "Bulan purnama"
    Array_indo += "Suatu malam"
    Array_indo += "Pada"
    Array_indo += "Dan"
    Array_indo += "Terhadap nasibnya"
    Array_indo += "Yang memperhatikan"
    Array_indo += "Seorang pun"
    Array_indo += "Di sana"
    Array_indo += "Tidaklah keadaannya"
    Array_indo += "Para tetangganya"
    Array_indo += "darinnya"
    Array_indo += "menjauhi"
    Array_indo += "sehingga"
    Array_indo += "menderita"
    Array_indo += "Dan"
    Array_indo += "Sangat miskin"
    Array_indo += "Nini anteh"
    Array_indo += "hidup"
    Array_indo += "keadaan"
    Array_indo += "Candramawat"
    Array_indo += "Nama panggilannya"
    Array_indo += "Telah diberi"
    Array_indo += "yang"
    Array_indo += "warna"
    Array_indo += "kucing"
    Array_indo += "tiga"
    Array_indo += "Mereka berdua memelihara"
    Array_indo += "Suami-istri itu"
    Array_indo += "Maka mulailah"
    Array_indo += "anak"
    Array_indo += "Keduanya memiliki"
    Array_indo += "tidak"
    Array_indo += "juga"
    Array_indo += "Akan tetapi"
    Array_indo += "Aki Balangantrang"
    Array_indo += "dengan"
    Array_indo += "nini"
    Array_indo += "menikah"
    Array_indo += "Yang lama"
    Array_indo += "waktu"
    Array_indo += "sejak"
    Array_indo += "Nini Anteh"
    Array_indo += "Dengan nama"
    Array_indo += "Yang dikenal"
    Array_indo += "Seorang perempuan"
    Array_indo += "dahulu"
    Array_indo += "zaman"
    Array_indo += "pada"
    Array_indo += "Tersebutlah"

    ArtiFull = "Tersebutlah pada zaman dahulu hidup seorang perempuan yang dikenal sebagai Nini Anteh. la menikah dengan Aki Balangantrang, sudah lama tidak memiliki anak. Karena sangat merindukan seorang anak, ia memelihara seekor kucing berbulu tiga warna, yang biasa dipanggil Candramawat.\n" +
            "\n" +
            "Kehidupan Nini anteh sangat miskin, Hidupnya sangat menderita. Para tetangganya menjauhinya. Ia tidak diperhatikan sama sekali malah selalu dihina. Tiada seorang pun yang iba terhadap nasibnya.\n" +
            "\n" +
            "Pada suatu malam, Nini Anteh memandang bulan yang menerangi bumi. Dalam benaknya ia membayangkan betapa tentramnya hidup di bulan. Sepertinya tak akan ada seorang pun yang menghina dan mencela kehidupannya lagi. Nini Anteh akhirnya menyampaikan hasratnya itu kepada Aki Balangantrang, suaminya. Ia juga mengatakan bahwa di bulan la akan menenun kain. Aki Balangantrang tidak bisa menolak keingan istrinya. Akhirnya Nini anteh pergi ke bulan ditemani   Candramawat\n" +
            "\n"

    val dongeng4: HalamanBelajar = HalamanBelajar("نيني أنتيه", "4. Nini Anteh", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

//    Dongeng 5
    Array_arab += "السَّاقِطِ"
    Array_arab += "اللَّيْمُونِ"
    Array_arab += "هَذَا"
    Array_arab += "الْتِقَاطِ"
    Array_arab += "مِنْ"
    Array_arab += "أَتَمَكَّنُ"
    Array_arab += "سَوْفَ"
    Array_arab += "رُبَّمَا"
    Array_arab += "عَلى قَيْدِ الحَيَاةِ"
    Array_arab += "زِلْتُ"
    Array_arab += "لَوْ"
    Array_arab += "الْقَبْرِ"
    Array_arab += "دَاخِلُ"
    Array_arab += "هُوَ"
    Array_arab += "وَ"
    Array_arab += "كَابَايَانْ"
    Array_arab += "فَقَالَ"
    Array_arab += "قَبْرِهِ"
    Array_arab += "فَوْقَ"
    Array_arab += "اللَّيْمُونِ"
    Array_arab += "ثِمَارُ"
    Array_arab += "سَقَطَتْ"
    Array_arab += "الدَّفْنِ"
    Array_arab += "بَعْدَ"
    Array_arab += "وَ"
    Array_arab += "فِيهَا"
    Array_arab += "نَفْسِهِ"
    Array_arab += "دَفْنِ"
    Array_arab += "وَ"
    Array_arab += "الْأَرْضِ"
    Array_arab += "بِحَفْرِ"
    Array_arab += "سِي كَابَايَانْ"
    Array_arab += "فَقَامَ"
    Array_arab += "اللَّيْمُونِ"
    Array_arab += "شَجَرَةِ"
    Array_arab += "تَحْتَ"
    Array_arab += "هُنَا"
    Array_arab += "أَنْ أَنْتَحِرَ"
    Array_arab += "أُرِيدُ"
    Array_arab += "كَابَايَانْ"
    Array_arab += "قَالَ"
    Array_arab += "النَّاضِجَةِ"
    Array_arab += "وَ"
    Array_arab += "الْمُثْمِرَةِ"
    Array_arab += "اللَّيْمُونِ"
    Array_arab += "شَجَرَةَ"
    Array_arab += "لَقِيَ"
    Array_arab += "بِالْمُصَادَقَةِ"
    Array_arab += "وَ"
    Array_arab += "الِانْتِحَارَ"
    Array_arab += "يَعْتَزِمُ"
    Array_arab += "سِي كَابَايَانْ"
    Array_arab += "كَانَ"
    Array_arab += "حَتَّى"
    Array_arab += "لِكَسَلَانِهِ"
    Array_arab += "الزَّوْجَةِ"
    Array_arab += "مِنْ"
    Array_arab += "الْوَبْخُ"
    Array_arab += "تَكَرَّرَ"
    Array_arab += "يَوْمٍ"
    Array_arab += "كُلَّ"
    Array_arab += "زَوْجَتُهُ"
    Array_arab += "حَسَمَتْ"
    Array_arab += "هَكَذَا"
    Array_arab += "الْأَكْلَ"
    Array_arab += "مِنِّى"
    Array_arab += "لَا تَطْلُبْ"
    Array_arab += "الْعَمَلِ"
    Array_arab += "فِي"
    Array_arab += "لَا تَرْغَبُ"
    Array_arab += "كُنْتَ"
    Array_arab += "إِذَا"
    Array_arab += "زَوْجَتُهُ"
    Array_arab += "وَبَخَتْهُ"
    Array_arab += "يَوْمٍ"
    Array_arab += "كُلُّ"
    Array_arab += "وَلِذَلِكَ"
    Array_arab += "الْعَمَلَ"
    Array_arab += "لَا يُرِيدُ"
    Array_arab += "كَسْلَانًا"
    Array_arab += "رَجُلًا"
    Array_arab += "سِي كَابَايَانْ"
    Array_arab += "كَانَ"
    init_arabic()

    Array_indo += "Yang jatuh"
    Array_indo += "limus"
    Array_indo += "ini"
    Array_indo += "memungut"
    Array_indo += "dari"
    Array_indo += "Saya bisa"
    Array_indo += "akan"
    Array_indo += "mungkin"
    Array_indo += "Masih hidup"
    Array_indo += "Aku tetap"
    Array_indo += "andaikata"
    Array_indo += "kubur"
    Array_indo += "Di dalam"
    Array_indo += "Dia itu"
    Array_indo += "dan"
    Array_indo += "kabayan"
    Array_indo += "Maka berkata"
    Array_indo += "Kuburannya"
    Array_indo += "Di atas"
    Array_indo += "Limus"
    Array_indo += "Buah"
    Array_indo += "Jatuhlah"
    Array_indo += "Mengubur diri"
    Array_indo += "Setelah"
    Array_indo += "dan"
    Array_indo += "Pada (tanah)nya"
    Array_indo += "dirinya"
    Array_indo += "mengubur"
    Array_indo += "dan"
    Array_indo += "tanah"
    Array_indo += "menggali"
    Array_indo += "Si kabayan"
    Array_indo += "Maka mulai"
    Array_indo += "Limus"
    Array_indo += "Pohon"
    Array_indo += "Di bawah"
    Array_indo += "Di sini"
    Array_indo += "Bunuh diri"
    Array_indo += "Aku ingin"
    Array_indo += "kabayan"
    Array_indo += "berkata"
    Array_indo += "Cukup masak"
    Array_indo += "dan"
    Array_indo += "Yang lebat"
    Array_indo += "Limus"
    Array_indo += "Pohon"
    Array_indo += "Ada (bertemu)"
    Array_indo += "kebetulan"
    Array_indo += "dan"
    Array_indo += "Bunuh diri"
    Array_indo += "bermaksud"
    Array_indo += "Si kabayan"
    Array_indo += "keadaan"
    Array_indo += "sehingga"
    Array_indo += "Karena kemalasannya"
    Array_indo += "istrinya"
    Array_indo += "dari"
    Array_indo += "teguran"
    Array_indo += "Terulang"
    Array_indo += "Hari"
    Array_indo += "Setiap"
    Array_indo += "Istrinya"
    Array_indo += "Memutuskan (tegas)"
    Array_indo += "demikian"
    Array_indo += "Makan"
    Array_indo += "Dariku"
    Array_indo += "Jangan meminta"
    Array_indo += "Bekerja"
    Array_indo += "dalam"
    Array_indo += "Tidak mau"
    Array_indo += "Keadaanmu"
    Array_indo += "Jika"
    Array_indo += "Istrinya"
    Array_indo += "Memarahinya"
    Array_indo += "Hari"
    Array_indo += "Setiap"
    Array_indo += "Karenanya"
    Array_indo += "Bekerja"
    Array_indo += "(ia) tidak mau"
    Array_indo += "Yang malas"
    Array_indo += "Seorang laki-laki"
    Array_indo += "Si Kabayan"
    Array_indo += "Adalah"

    ArtiFull = "SI KABAYAN orang malas, tak mau bekerja. Karenanya, tiap hari ia dimarahi istrinya.\n" +
            "“Jangan ingin makan kalau kamu tidak mau bekerja!” Tegas istrinya.\n" +
            "Karena terus dimarahi, si Kabayan bermaksud bunuh diri. Kebetulan ada pohon limus (sejenis buah mangga) yang sedang berbuah lebat dan cukup masak.\n" +
            "“Ah, bunuh dirinya di sini saja,” ujarnya.\n" +
            "Si Kabayan kemudian menggali tanah dan mengubur diri. Tak lama kemudian jatuhlah buah limau mengenai badannya.\n" +
            "Wah, andaikata saya masih hidup, mungkin saya bisa memungut buah-buah limus ini.\n"

    val dongeng5: HalamanBelajar = HalamanBelajar("سي كابايان تُرِيدُ اللّيْمُوْنَ", "5. Sikabayan Ingin Buah Limau", resultArray ,Array_indo.reversedArray(), Array_arab.reversedArray(), Array_logat,  ArtiFull , Array_logat_B, Array_Duplicate ,Penjelasan)
    clearArrays()

    Dongeng += listOf(dongeng1, dongeng2, dongeng3, dongeng4, dongeng5)

//    taroh sini buat List dongengnya
    Dongeng += listOf()

    sizehd = Hadist.size
    sizedg = Dongeng.size
}


fun get_sizehd(): Int{
    return sizehd
}

fun get_sizedg(): Int{
    return sizedg
}

fun get_Hadist(): List<HalamanBelajar>{
    return Hadist
}

fun get_Dongeng(): List<HalamanBelajar>{
    return Dongeng
}

